### ISSUE TITLE
Extension is Autofollowing channels

### ISSUE THREAD

**Issue by enhazappe** [WeaselStorm/ChannelPointCollector#7] opened 2022-01-02 09:13 UTC
**Describe the bug**
When visiting a stream, extension automatically clicks popup in chat window for following a channel.

**To Reproduce**
1. Go to channel you are not following
2. You are now following a channel

**Expected behavior**
Should not follow a channel, or perhaps add setting to turn this on as optional

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: firefox
 - Version: 95.0.2 64bit

**Comment by WeaselStorm** [comment] 2022-01-02 09:16
Do you happen to have the channel you noticed the issue on? I'm wondering if it has something to do with follower emotes or follower only chat.

**Comment by enhazappe** [comment] 2022-01-02 09:47
I tried several channels, as its instantaneous i cannot verify if its only due to follower only chat, but the root cause is the popup in chat.

channels i know it followed for me:
https://www.twitch.tv/yourprincess
https://www.twitch.tv/arrowioi

**Comment by Shamdex** [comment] 2022-01-02 15:20
I can confirm to having this issue as well. The streamer it most recently followed has slowmode activated, not follower only chat. It was also a raid for what that may be worth.

https://www.twitch.tv/geekseh?referrer=raid

**Comment by WeaselStorm** [comment] 2022-01-02 16:55
Thanks guys, I see the root cause of the issue, it's definitely a chat pop-up advertising follower emotes. It's a bit odd since I've been doing most of my development and testing as a Chrome extension and I never can seem to get that pop-up there. 🤷

I'll try to get that patched up and tested today.

**Comment by WeaselStorm** [comment] 2022-01-03 01:57
Fixed in release v0.0.10 which is live on FF add-ons

**Closed by WeaselStorm** 2022-01-03 01:57 UTC
